name: Check for go mod changes
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Test go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
