name: Test External Git & Registry
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  merge_group:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-external-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-external:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          build-examples: "false"

      - name: Setup k3d
        uses: ./.github/actions/k3d

      - name: Cleanup files
        uses: ./.github/actions/cleanup-files

      - name: Run external service test
        run: make test-external

      - name: get cluster info
        uses: ./.github/actions/debug-cluster
        if: always()

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
