name: Test Unit Tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  merge_group:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  push:
    # Running unit tests on main gives codecov a base to compare PRs against
    branches:
      - main

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup golang
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make test-unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@985343d70564a82044c1b7fcb84c2fa05405c1a2 # v5.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
